#VARIABLES
src= .
inc= -I. -I../inc -I../abstract -I../heavy_net
obj= ../obj
flags= -Wall -g
cc= g++

#CIBLES

cmd = $(cc) -c $(inc) $(flags) $(src)/$@.cpp; mv $@.o $(obj)

unit:
	$(cmd)

synaptic:
	$(cmd)

synaptics:
	$(cmd)

models:
	$(cmd)

funcs:
	$(cmd)

activation:
	$(cmd)
